import axios from 'axios';
import { useEffect, useState } from 'react';
import React from 'react';
import Layout from '../Layout/Layout';
import { TOKEN_ID } from '../../utils/constants';
import { useAuth } from '../../context/AuthContext';
import DelegateCard from '../../components/DelegateCard/DelegateCard';
import Loader from '../Loader/Loader';

function loadScript(src) {
  return new Promise((resolve) => {
    const script = document.createElement('script');
    script.src = src;
    script.onload = () => {
      resolve(true);
    };
    script.onerror = () => {
      resolve(false);
    };
    document.body.appendChild(script);
  });
}

async function displayRazorpay(delegateCardID) {
  const res = await loadScript('https://checkout.razorpay.com/v1/checkout.js');
  console.log('Load Script ', res);
  if (!res) {
    alert('Razorpay SDK failed to load.');
    return;
  }

  //Helps start an order and register order with razorpay
  const resp = await axios.post(
    '/api/user/payment',
    {
      delCard_id: delegateCardID,
    },
    {
      headers: {
        authorization: localStorage.getItem(TOKEN_ID),
      },
    }
  );

  let data = resp.data.data;
  console.log('POST DATA : ', data);

  const options = {
    key: 'rzp_test_YwEGRlKoqLToxD',
    currency: data.currency,
    amount: String(data.amount),
    order_id: data.orderId, //OrderId generated by backend sent in response in previous get request
    name: data.name, //Name of Ticket/Card
    description: "Revels'22",
    // Logo Image
    image:
      'https://scontent.fixr3-2.fna.fbcdn.net/v/t1.6435-9/81363115_3254316291309114_9119946810595475456_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=z5N4zUOYsqgAX-DZ3CE&_nc_ht=scontent.fixr3-2.fna&oh=00_AT8fP09Jreo-FiZHchIMQKb806mPWPs0rrg-ovT91MFfEQ&oe=622F8575',
    prefill: {
      name: 'userName', //Enter Logged In User details to be prefilled in checkout form
      email: 'test@test.com',
      contact: '919999999999',
    },

    // After Checkout following Handler is called which confirms payment is made to backend
    // Alternatively in production can be done using Razorpay web-hooks -- (Better but can be used only in production) -- backend route for the same is ready
    handler: function (response) {
      console.log('Response Razorpay', response);
      axios
        .post(
          '/api/user/payment/verify',
          {
            order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
          },
          {
            headers: {
              authorization: localStorage.getItem(TOKEN_ID),
            },
          }
        )
        .then((resp) => {
          if (resp.data.success) {
            alert('Payment successful');
          } else {
            alert('Payment Failed');
          }
        });
    },
  };
  console.log('Payment Initiated');

  //Finally opens checkout window and where user pays for registered order
  const paymentObject = new window.Razorpay(options);
  paymentObject.open();
}

function DelegatePage() {
  const [delegateCard, setDelegateCard] = useState([]);
  const auth = useAuth();
  const user = auth.user; 
  const isMyDelCard = (delCardId) => {
    if(user.delegateCards.includes(delCardId)){
      return true;
    } else {
      return false;
    }
  }
  useEffect(() => {
    // To get all types of proshow and non proshow
    const fetchDelegateCards = async () => {
      const resp = await axios.get(
        '/api/user/delegatecard/getall'
      );
      console.log('DATA ', resp.data);
      setDelegateCard(resp.data.data);
    }
    fetchDelegateCards();
  }, []);
  const colorArr = ['blue', 'purple', 'black'];
  return (
    auth.loading ? <Loader /> :
    <Layout activeTab={'delegate-card'}>
      <div className="delegate-container">
        <div className="d-flex flex-md-row flex-column flex-wrap m-0 p-0">
          {delegateCard.map((data, index) => {
            return (
              <DelegateCard
                key={index} 
                colorArr={colorArr} 
                idx={index} 
                displayRazorpay={displayRazorpay} 
                data={data} 
                isMahe={user.isMahe}
                isBought={isMyDelCard(data._id)}
              />
            );
          })}
        </div>
      </div>
    </Layout>
  );
}

export default DelegatePage;
