import { useEffect, useState } from 'react';
import React from 'react';
const axios = require('axios');

function loadScript(src) {
  return new Promise((resolve) => {
    const script = document.createElement('script');
    script.src = src;
    script.onload = () => {
      resolve(true);
    };
    script.onerror = () => {
      resolve(false);
    };
    document.body.appendChild(script);
  });
}

async function displayRazorpay(delegateCardID) {
  const res = await loadScript('https://checkout.razorpay.com/v1/checkout.js');
  console.log('Load Script ', res);
  if (!res) {
    alert('Razorpay SDK failed to load.');
    return;
  }

  //Helps start an order and register order with razorpay
  const resp = await axios.post('http://localhost:5000/api/user/payment', {
    delCard_id: delegateCardID,
  });

  let data = resp.data.data;
  console.log('POST DATA : ', data);

  const options = {
    key: 'rzp_test_YwEGRlKoqLToxD',
    currency: data.currency,
    amount: String(data.amount),
    order_id: data.orderId, //OrderId generated by backend sent in response in previous get request
    name: data.name, //Name of Ticket/Card
    description: "Revels'22",
    // Logo Image
    image:
      'https://scontent.fixr3-2.fna.fbcdn.net/v/t1.6435-9/81363115_3254316291309114_9119946810595475456_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=z5N4zUOYsqgAX-DZ3CE&_nc_ht=scontent.fixr3-2.fna&oh=00_AT8fP09Jreo-FiZHchIMQKb806mPWPs0rrg-ovT91MFfEQ&oe=622F8575',
    prefill: {
      name: 'userName', //Enter Logged In User details to be prefilled in checkout form
      email: 'test@test.com',
      contact: '919999999999',
    },

    // After Checkout following Handler is called which confirms payment is made to backend
    // Alternatively in production can be done using Razorpay web-hooks -- (Better but can be used only in production) -- backend route for the same is ready
    handler: function (response) {
      console.log('Response Razorpay', response);
      axios
        .post('http://localhost:5000/api/user/payment/verify', {
          order_id: response.razorpay_order_id,
          razorpay_payment_id: response.razorpay_payment_id,
          razorpay_signature: response.razorpay_signature,
        })
        .then((resp) => {
          if (resp.data.success) {
            alert('Payment successful');
          } else {
            alert('Payment Failed');
          }
        });
    },
  };
  console.log('Payment Initiated');

  //Finally opens checkout window and where user pays for registered order
  const paymentObject = new window.Razorpay(options);
  paymentObject.open();
}

function DelegateCard() {
  async function fetchDelegateCards() {
    // To get all types of proshow and non proshow
    let resp = await axios.get(
      'http://localhost:5000/api/user/delegatecard/getall'
    );
    console.log('DATA ', resp.data);
    setDelegateCard([...resp.data.data]);
  }
  const [delegateCard, setDelegateCard] = useState([
    {
      name: '',
      isProShow: '',
      mahePrice: '',
      nonMahePrice: '',
      isActive: '',
      description: '',
      _id: '',
    },
  ]);
  useEffect(() => {
    fetchDelegateCards();
  }, []);

  return (
    <div>
      {delegateCard.map((delCard) => {
        let {
          name,
          isProShow,
          mahePrice,
          nonMahePrice,
          isActive,
          description,
          _id,
        } = delCard;
        return (
          <div className="delegate-container">
            <p className="title">Delegate Cards</p>
            <div className="del-flex">
              <div className="delcardblue">
                <h1 style={{ color: 'white' }}>SPORTS</h1>
                <p style={{ color: 'white', marginTop: '10px' }}>
                  {/* Name : {name} <br />
                  isProShow : {isProShow} <br />
                  MAHE-Price: {mahePrice} <br />
                  NON-MAHE Price : {nonMahePrice} <br />
                  description : {description} <br /> */}
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries, but
                  also the leap into electronic typesetting, remaining
                  essentially unchanged. It was popularised in the 1960s with
                  the release of Letraset sheets containing Lorem Ipsum
                  passages, and more recently with desktop publishing software
                  like Aldus PageMaker including versions of Lorem Ipsum.
                  <div className="collegetype">
                    <div className="clg">
                      MAHE STUDENTS
                      <center>Rs 250</center>
                    </div>
                    <div className="clg">
                      NON-MAHE STUDENTS
                      <center>Rs 350</center>
                    </div>
                  </div>
                  <center>
                    <button onClick={() => displayRazorpay(_id)}>
                      BUY NOW
                    </button>
                  </center>
                </p>
              </div>
              <div className="delcardblack">
                <h1 style={{ color: 'white' }}>CULTURAL</h1>
                <p style={{ color: 'white', marginTop: '10px' }}>
                  {/* Name : {name} <br />
                  isProShow : {isProShow} <br />
                  MAHE-Price: {mahePrice} <br />
                  NON-MAHE Price : {nonMahePrice} <br />
                  description : {description} <br /> */}
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries, but
                  also the leap into electronic typesetting, remaining
                  essentially unchanged. It was popularised in the 1960s with
                  the release of Letraset sheets containing Lorem Ipsum
                  passages, and more recently with desktop publishing software
                  like Aldus PageMaker including versions of Lorem Ipsum.
                  <div className="collegetype">
                    <div className="clg">
                      MAHE STUDENTS
                      <center>Rs 250</center>
                    </div>
                    <div className="clg">
                      NON-MAHE STUDENTS
                      <center>Rs 350</center>
                    </div>
                  </div>
                  <center>
                    <button onClick={() => displayRazorpay(_id)}>
                      BUY NOW
                    </button>
                  </center>
                </p>
              </div>
              <div className="delcardpurple">
                <h1 style={{ color: 'white' }}>PROSHOW</h1>
                <p style={{ color: 'white', marginTop: '10px' }}>
                  {/* Name : {name} <br />
                  isProShow : {isProShow} <br />
                  MAHE-Price: {mahePrice} <br />
                  NON-MAHE Price : {nonMahePrice} <br />
                  description : {description} <br /> */}
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries, but
                  also the leap into electronic typesetting, remaining
                  essentially unchanged. It was popularised in the 1960s with
                  the release of Letraset sheets containing Lorem Ipsum
                  passages, and more recently with desktop publishing software
                  like Aldus PageMaker including versions of Lorem Ipsum.
                  <div className="collegetype">
                    <div className="clg">
                      MAHE STUDENTS
                      <center>Rs 250</center>
                    </div>
                    <div className="clg">
                      NON-MAHE STUDENTS
                      <center>Rs 350</center>
                    </div>
                  </div>
                  <center>
                    <button onClick={() => displayRazorpay(_id)}>
                      BUY NOW
                    </button>
                  </center>
                </p>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default DelegateCard;
